### ISSUE TITLE
Trouble building lucet-wasi (467 errors)

### ISSUE THREAD

**Issue by cryptoquick** [fastly/lucet#104]
I'm having a really difficult time building `lucet-wasi` on Arch Linux.

After reading #78 I installed the dependencies I could (hwloc, llvm, lld using pacman), and I also tried my best to install wasi-sdk, which wouldn't compile no matter how much I tried, so I had to take the .deb and use debtap to create an arch pkg.

The commands I ran were:

```
git clone --recurse-submodules git@github.com:fastly/lucet.git
cd lucet/lucet-wasi
cargo build
```

I also tried `cargo +nightly build --verbose`. I've done a lot more than this, but I'm trying to pare the noise down. I'm out of things I know how to try.

A couple screenshots that might help... Errors with `cargo build`:

![Screenshot from 2019-04-06 19-59-28](https://user-images.githubusercontent.com/285690/55677551-444a1800-58a7-11e9-8c90-7fc62624b061.png)

Errors building `wasi-sdk`:

![Screenshot from 2019-04-06 19-53-34](https://user-images.githubusercontent.com/285690/55677552-4a3ff900-58a7-11e9-8c8d-cb04a32b6fb7.png)

Any help is appreciated...

**Comment by jedisct1** [comment]
Regarding `wasi-sdk`: since you are running Arch Linux, you don't need it, as the distribution already provides an up to date LLVM toolchain with support for webassembly.

Clone this subset instead: https://github.com/CraneStation/wasi-sysroot

`pacman -S clang llvm lld` is all you need to compile this (if you get an error about `llvm-ar` not being found, this is because you installed `clang` but not the whole `llvm` package).

`make install` will install the WASI sysroot in `/usr/local` which may be a bit intrusive. Edit the main `Makefile` and change `INSTALL_DIR` in order to change this.

`lucet-wasi` has the `/opt/wasi-sdk` path hard-coded, but that can be changed by setting a `WASI_SDK` environment variable. The examples need other variables: `WASI_CC` and `WASI_LD`, that you can simply set to the path to the normal `clang` and `llvm-ld` binaries installed on your system.

The Lucet tools themselves are only tested using Rust-stable (currently `1.33.0`). 

Some will break if surprising ways (such as `__wasi*` symbols not being found) if `WASI_SDK` is not defined. So, define that one :)

HIH.

**Comment by jedisct1** [comment]
The only thing that you may find missing is the `/usr/lib/clang/8.0.0/lib/wasi/libclang_rt.builtins-wasm32.a` file.

Unless you want to recompile `clang` specifically for this, you can just extract that file from the `wasi-sdk` Debian package (it's located in `opt/wasi-sdk/lib/clang/8.0.0/lib/wasi/`) and copy it to the path Arch Linux expects it at.

**Comment by jedisct1** [comment]
Speaking of the `libclang_rt.builtins-wasm32.a` file: you may also want to add a symlink to it in `/usr/lib/clang/8.0.0/lib/` as well (not just in the `wasi/`) subdirectory.

Since `wasi` is not recognized by tools such as `autotools` yet, this will let you use the `wasm32-unknown-none` triple as an alternative to `wasm32-unknown-wasi`. More software will compile out of the box that way.

**Comment by cryptoquick** [comment]
Thank you for the detailed responses so far!

The `wasi-sysroot` compile went well, thanks for the direction. I opted to leave the makefile as-is, and just use the environment variables you mentioned.

So, in the lucet-wasi subfolder, I tried running the following command that I cooked up as best I could follow:

```sh
WASI_SDK=/usr/local \
WASI_CC=/usr/bin/clang \
WASI_LD=/usr/bin/lld \
cargo build
```

I think I got something wrong though. Check it out:

![Screenshot from 2019-04-07 07-02-47](https://user-images.githubusercontent.com/285690/55684008-9fa9f380-5903-11e9-9717-a9cfd406c711.png)

**Comment by jedisct1** [comment]
This is likely to happen because build scripts still assume that `clang` emits webassembly code by default, but this is only true in the Docker image, and with a specific `clang`. The `--sysroot` and `--target` parameters are missing.

Portability is not great yet, but this is something we will improve, especially to support Linux distributions that already ship with an up-to-date LLVM toolchain.

**Comment by jedisct1** [comment]
`lucet-wasi/build.rs` has quite a lot of hard-coded paths that you may want to change.

**Comment by jedisct1** [comment]
I was able to compile it on Arch with the following changes to `build.rs`.

Change `/tmp/sysroot` to where you installed WASI.

```diff
diff --git a/lucet-wasi/build.rs b/lucet-wasi/build.rs
index b51ec31..ddb2cf2 100644
--- a/lucet-wasi/build.rs
+++ b/lucet-wasi/build.rs
@@ -4,9 +4,7 @@ use std::path::{Path, PathBuf};
 use std::process::{Command, Stdio};
 
 fn main() {
-    let wasi_sdk =
-        Path::new(&env::var("WASI_SDK").unwrap_or("/opt/wasi-sdk".to_owned())).to_path_buf();
-    let wasi_sdk_core_h = wasi_sdk.join("share/sysroot/include/wasi/core.h");
+    let wasi_sdk_core_h = Path::new("/tmp/sysroot/include/wasi/core.h");
 
     println!("cargo:rerun-if-changed={}", wasi_sdk_core_h.display());
 
@@ -28,11 +26,10 @@ fn main() {
     let host_builder = bindgen::Builder::default()
         .clang_arg("-nostdinc")
         .clang_arg("-D__wasi__")
-        .clang_arg(format!(
-            "-isystem={}/share/sysroot/include/",
-            wasi_sdk.display()
-        ))
-        .clang_arg(format!("-I{}/lib/clang/8.0.0/include/", wasi_sdk.display()))
+        .clang_arg(
+            "-isystem=/tmp/sysroot/include/"
+        )
+        .clang_arg("-I/usr/lib/clang/8.0.0/include")
         .header(core_h_path.to_str().unwrap())
         .whitelist_type("__wasi_.*")
         .whitelist_var("__WASI_.*");
```

**Comment by cryptoquick** [comment]
@jedisct1 Nice, okay, I'll experiment with that when I get some time to do so. But in the meantime, is there an issue tracking portability issues like this? Perhaps it should be referenced.

**Comment by cryptoquick** [comment]
And thank you so much for your time and attention to detail! You're on the level!
