### ISSUE TITLE
Interpreting Sightglass / Shootout results

### ISSUE THREAD

**Issue by jlb6740** [fastly/lucet#107]
Hi ... Is it the case that the metric for all tests in shoot out is elapsed time? When I see results below should I assume that any ratio number above the reference of 1 means that shootout test took longer with the c->wasm->native path than the reference path of c->native?

On my system I see a few tests were the c->wasm->native is actually reporting a ratio number below 1. Does this mean those benchmarks performed better when converted to WASM?  Where are the raw numbers and binaries used to collect the numbers stored?

```
 Test        | Implementation | Ratio              | Median       | RSD
 ------------+----------------+--------------------+--------------+--------------------
 ackermann   | Reference      | 1                  | 523107       | 10.76839249381212
 ackermann   | lucet          | 2.6516361035666582 | 1456198      | 4.788126703819359
 base64      | Reference      | 1                  | 176240154.5  | 2.916611227769061
 base64      | lucet          | 1.464050958766964  | 264776860.5  | 4.060475088333558
 ctype       | Reference      | 1                  | 277633475.5  | 4.125341827565504
 ctype       | lucet          | 2.827206041953314  | 785632288    | 5.859557592784653
 ed25519     | Reference      | 1                  | 830979983    | 1.7771897005923085
 ed25519     | lucet          | 7.705137365616381  | 6466526145   | 0
```

Thanks!

**Comment by pchickey** [comment]
Yes, your understanding of the ratios output by sightglass are correct.

The binaries used to collect the measurements are built by `benchmarks/shootout/Makefile` and live in `benchmarks/shootout/build`. Sightglass loads and executes `benchmarks/shootout/build/lucet/implementation.so` and `benchmarks/shootout/build/native/implementation.so`, as described in `benchmarks/shootout/sightglass.toml`.

Currently, sightglass does not emit the measurements. That feature could be added if you require it, but please file an issue about it on the sightglass repo: https://github.com/fastly/sightglass

**Comment by jlb6740** [comment]
@pchickey ... Thanks a lot. I am curious about some of these numbers now where WASM actually performs better. 

> Currently, sightglass does not emit the measurements. That feature could be added if you require it, but please file an issue about it on the sightglass repo: https://github.com/fastly/sightglass

Ok, so sounds like there is no convenient way to get the execution time for the benchmarks, just ratios. If that is the case I'll file an issue/feature request there. 

Thanks!

**Comment by jedisct1** [comment]
The JSON output has way more data than the `TEXT` and `CSV` outputs.

**Comment by awortman-fastly** [comment]
FWIW @jlb6740 the comparisons where lucetc/cranelift perform better are exactly as you read them - the following is what I saw last week with gcc, though numbers were similar through `CC=clang` so I imagine something similar is done there:

`nestedloop3` (and probably `nestedloop2`, though I didn't look at it) seems to run afoul of some loop transformation in gcc and has (what seem to be) loop counters in an avx2 register, then extracts a word out of the register inside the innermost loop. Cranelift generates pretty unsurprising code here, so I imagine that particular avx2 use is the cause of most of the difference

`switch2` is really interesting because by gcc the cases turn into a lightly suspect
```
mov rcx, rax
add rcx, qword [rsp + 0x10]
xor dword [rcx], <imm32>
```
where cranelift produces
```
    [snip]
    mov ebx, edi
A:
    xor ebx, <imm32>
    mov edi, esi
    mov r8, qword [rsp + 0x28]
    mov dword [r8 + rdi], ebx
    jmp B
    mov ebx, edi
B:
    xor ebx, <next_imm32>
```

I *think* the major difference here is that gcc results in three memory accesses per case (read for the `add` and read + write for `xor`) where cranelift does two. That only explains some of the difference, and I'm left with nothing but a guess that cranelift's read-only behavior with memory in the switch brings the rest.

In both cases I'm pretty sure all memory accesses could be hoisted out of the switch but none of {cranelift,gcc,clang} do that, which is interesting.

**Comment by jlb6740** [comment]
Hi @awortman-fastly thanks for the insights. I was wondering in those results where WASM was better, if cranelift or lucid was doing something special here to accelerate things but it sounds like in these cases gcc is simply not producing optimal code. All of these results are interesting and warrant analysis.
