### ISSUE TITLE
xenial is old Ubuntu LTS is bionic

### ISSUE THREAD

**Issue by alterstep** [fastly/lucet#137]
https://github.com/fastly/lucet/blob/d0f07b5dc2a7cfa8a9dbc4906b5a6505de69bb52/Dockerfile#L1

why old version? All docker images with a LTS Ubuntu base use bionic.

**Comment by jedisct1** [comment]
Good to see you here :)

Xenial is old, but still supported. This is what we use internally.

Since we side install the latest stable Rust version as well as an up-to-date LLVM toolchain, the base system doesn't matter much.

I verified that Lucet builds and works fine on Ubuntu 18.04 and 19.04 in addition to version 16.04 (xenial).

So, really, the only downside of still using Xenial is that if the other images you are using are all based on Bionic, Docker will download Xenial instead of reusing an existing base layer.

But from a functional perspective, there won't be any differences. And, as I previously pointed out, Xenial is still supported.

The current image will be split into two images, one for Lucet hackers, and another one for people who only want to use the tools. The former is likely to stick to Xenial, but the later can either use something more recent (not necessarily Ubuntu) in order to use the stock LLVM install.
