### ISSUE TITLE
heap doesn't grow or I don't understand lucetc --min-reserved-size

### ISSUE THREAD

**Issue by alterstep** [fastly/lucet#145]
# problem
heap doesn't grow.

# test case

```c
int main(void) {
  printf("%p\n", malloc(4 * 1024 * 1024)); // 4 MiB
  return 0;
}
```

-> fails without `lucetc --min-reserved-size 5MiB` or more

but `max-reserved-size` is 4 GiB.

# expected

heap grows dynamically. Starts at `min-reserved-size`, but can grow.

**Comment by acfoltzer** [comment]
We should definitely clarify the documentation on this. The reserved size arguments for `lucetc` specify how big the reserved size _can_ be when the module is executed, not where the heap size starts at runtime.

Different wasm modules will require different amounts of initial heap size, before the heap grows dynamically. If you set `--min-reserved-size` to zero, the compiled module will have a reserved size limit equal to the initial size it requires. Likewise, if you set `--max-reserved-size` lower than the initial size, the module will fail to compile. This is a means of statically enforcing that a module's heap will never grow past a certain size, even if more resources are available at runtime.

Controlling the size of the heap dynamically is done through the `--max-heap-size` argument to `lucet-wasi`, or through the `Limits` arguments to the memory region creation, if you're running modules programmatically.

The fact that these options sound very similar but do subtly different things is definitely a UI wart we should work on.

**Comment by jedisct1** [comment]
if `min-reserved-size` and `max-heap-size` are the same, why different names?
and if `min-reserved-size` is the max memory for the module, what is `max-reserved-size`?
this is not clear at all. perhaps these options need a better name.

**Comment by acfoltzer** [comment]
The problem is we have bounds at compile time and at runtime, and we combine these together as we proceed through the stages.

`lucetc` provides a reserved size, which represents an upper bound for heap size at runtime. If the initial heap size falls between `min-reserved-size` and `max-reserved-size`, then the reserved size is equal to the initial heap size. If it is smaller, the reserved size is equal to `min-reserved-size`. If the initial heap is larger than `max-reserved-size`, the module fails to compile. Terrarium is an example of a scenario where this is useful, because it lets us limit the amount of memory used by a program before it even gets deployed and run.

Meanwhile, `MmapRegion` in `lucet-runtime` is created with `Limits`. The limits might be lower than the `lucetc` module reserved size. The maximum size of the heap at runtime is the lower of these two bounds. A single region can hold instances created from many different modules, so these limits are distinct in order to provide limits for the region as a whole. This again useful in a system like Terrarium when we want to limit the overall memory usage of the server.

In the case of a region which holds a single module like `lucet-wasi`, this distinction is much harder to see. Making these bounds distinct isn't necessary for that case, so maybe we could simplify it.

**Comment by alterstep** [comment]
```c
printf("%p\n", malloc(4 * 1024 * 1024)); // 4 MiB
```

# without lucet options

thread `main` panicked

```
thread 'main' panicked at 'lucet-wasi runtime error: Runtime fault: FaultDetails { fatal: false, trapcode: TrapCode { ty: HeapOutOfBounds, tag: 0 }, rip_addr: 140614615088071, rip_addr_details: Some(AddrDetails { in_module_code: true, file_name: Some("/lucet/a.so"), sym_name: None }) }', lucet-wasi/src/main.rs:196:23
```

# with lucet --heap-size=4MiB

returns NULL

```
0
```

**Comment by alterstep** [comment]
# Expected

returns NULL.

**Comment by jedisct1** [comment]
Lucetc's `min-reserved-size` value affects the generated code.

Namely, the generated code assumes that the heap will never be more than `min-reserved-size`.

Here's a simple wasm function that tries to access address 0x400000 (4 Mb):

```wat
  (func $__original_main (type 4) (result i32)
    i32.const 0
    i32.const 42
    i32.store8 offset=4194304
    i32.const 0)
```

Here's the code generated by lucetc with the default `min-reserved-size` value:

```asm
_guest_internalfunc___original_main:
     e68:       40 55   pushq   %rbp
     e6a:       48 89 e5        movq    %rsp, %rbp
     e6d:       0f 0b   ud2
```

`ud2` is a trap instruction, it forces the runtime to abort. The code always traps; it doesn't even try to access the pointer.

Not, with `min-reserved-size` set to 8Mb:

```asm
_guest_internalfunc___original_main:
     e48:       40 55   pushq   %rbp
     e4a:       48 89 e5        movq    %rsp, %rbp
     e4d:       40 b8 00 00 00 00       movl    $0, %eax
     e53:       40 b9 2a 00 00 00       movl    $42, %ecx
     e59:       40 81 f8 fe ff 3f 00    cmpl    $4194302, %eax
     e60:       40 72 02        jb      2 <_guest_internalfunc___original_main+0x1d>
     e63:       0f 0b   ud2
     e65:       40 89 c0        movl    %eax, %eax
     e68:       40 88 8c 07 00 00 40 00         movb    %cl, 4194304(%rdi,%rax)
     e70:       40 b8 00 00 00 00       movl    $0, %eax
     e76:       40 5d   popq    %rbp
     e78:       c3      retq
```

Woah, way more things happening here :)

So: `min-reserved-size` generates hard-coded boundary checks. Even if the runtime would accept a larger heap, accessing data beyond `min-reserved-size` will trap.

Whereas `max-heap-size` controls the maximum heap allowed at run-time. Here, the code can catch and recover from a heap expansion that couldn't be done.

I think `min-reserved-size` and `max-heap-size` should usually be set to the same value.

If not, `max-heap-size` should always be less than `min-reserved-size`.
