### ISSUE TITLE
Overhead of creating a region?

### ISSUE THREAD

**Issue by singpolyma-shopify** [fastly/lucet#195]
So, I can create a region that can serve `n` instances, but if there are already that many instances running then trying to create a new one produces an error.

Or I can create a new 1-instance region for each instance I want to run.

In the former case I'm going to have to poll, essentially, until the region has space.

So I guess I'm wondering how to think about the overhead of these two scenarios: how expensive is the region creation really?

**Comment by pchickey** [comment]
We picked the region abstraction because, when using Lucet as part of a web service, we wanted to bound the resource consumption of Lucet programs. Besides bounding memory and address space use, creating memory maps is a relatively expensive system call so we wanted to amortize that across the life of the region, rather than do it per-instance.

We did not include primitives on regions to block until an element is available, but if there is a sensible way to do this (without adding significant overhead to users who don't need it) we could add it, rather forcing you to write a polling loop. I don't have enough experience with Rust concurrency to fully understand the design space.

In Terrarium (wasm.fastlylabs.com) we used a thread-pool web service with the same number of threads as the region holds instances, so the thread pooling mechanism ended up taking care of any contention for us.

**Comment by singpolyma-shopify** [comment]
That's an interesting approach.  So far I've been using tokio/hyper so I don't think there's the same kind of hard bound on connections in progress as with a threadpool-based server, but given the limits necessary with mmap anyway, it might make sense for me to switch.
