### ISSUE TITLE
lucet-analyze is broken - crashes when reading the function indirection table

### ISSUE THREAD

**Issue by shravanrn** [fastly/lucet#300]
Lucet-analyze crashes when trying to parse the function indirection table. While I haven't traced through exactly why this is happening, the crux of the crash seems to come from [here](https://github.com/fastly/lucet/blob/master/lucet-analyze/src/main.rs#L499). The code is somehow treating the table offset as a pointer and trying to dereference it causing a segfault

**Comment by awortman-fastly** [comment]
oops! good catch. `lucet-analyze` has been plagued with this specific kind of bug because it works with modules as they exist at rest, not as a properly mapped ELF library, so pointers are pretty consistently incorrect.

I don't recall if there's a reason we don't `dlopen` the artifact and operate on that.. It would be a lot less bug prone.

**Comment by pchickey** [comment]
I think the idea was that we wanted to inspect the ELF file without giving it the opportunity to execute code or crash the linker/loader, either of which could happen with a malicious file. But it is pretty confusing and difficult to manage.

It was invented before the `lucet-module` abstraction, which now makes extracting all this metadata a lot easier. Back when lucet-analyze was first written, the only other decoder of the serialized module metadata was part of the C runtime.

Maybe we should redesign the tool to use dlopen, though.

While we're reinventing it, is lucet-objdump a more obvious name?

**Comment by awortman-fastly** [comment]
Avoiding extra loader involvement makes sense, though I severely hope we never happen upon an object that crashes the loader.. Being able to reliably use lucet-analyze on possibly-malicious inputs makes sense. I don't know Linux loader bits enough to have a feel if dlopen might also run any kind of static initializers, and there _is_ that paper about ELF relocations being Turing complete..

At the very least it's probably due for a test suite to avoid this kind of bug getting by.

As far as names go, I don't have terribly strong opinions either way, but I pretty often reach for `-d` in tools named `*objdump`.

But! This bug is fixed so I'm going to close the issue.
