### ISSUE TITLE
Issue compiling lucet-runtime crate on osx

### ISSUE THREAD

**Issue by DuncanUszkay1** [fastly/lucet#339]
Hello- just recently updated my version of lucet-runtime and I can't seem to get it to compile on my machine. It compiles just fine on Debian.

Using MacOS Mojave 10.14.6, rust version 1.38.0

Error: 
```
  = note: Undefined symbols for architecture x86_64:
            "instance_kill_state_exit_guest_region", referenced from:
                _lucet_context_backstop in liblucet_runtime_internals-bc22c96bf26a7eaa.rlib(context_asm.o)
               (maybe you meant: _instance_kill_state_exit_guest_region)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)


error: aborting due to previous error

error: Could not compile `lucet-runtime`.
```

Any ideas?

**Comment by acfoltzer** [comment]
Hi @DuncanUszkay1, the patch we just landed in #338 ought to fix this specific issue. However I will note that there are currently some other outstanding bugs with the experimental Mac OS support that you might run into (e.g., #323).

Please let me know if this helps!

**Comment by awortman-fastly** [comment]
I wrote some bad assembly, sorry! I don't think that function is made public by the crate, so even though it was `#[no_mangle]`, it got a leading `_`, so the symbol [here](https://github.com/fastly/lucet/commit/fac8ee596846847ce24e06da987378440c8ba7e6#diff-adb782ea0cfdba94fce93722c7e66267L79 should in fact have been `__instance_kill_state_exit_guest_region`.

This is all moot as of [19 minutes ago](https://github.com/fastly/lucet/pull/338) because that code was rewritten!

**Comment by DuncanUszkay1** [comment]
Ah yep that did the trick. Thanks guys!
