### ISSUE TITLE
Error when using lucet-runtime

### ISSUE THREAD

**Issue by lostman** [fastly/lucet#73]
I tried the example from:
https://github.com/fastly/lucet/blob/master/lucet-runtime/src/lib.rs

```
use lucet_runtime::{DlModule, Limits, MmapRegion, Region};

fn main() {
    let module = DlModule::load("hello.so").unwrap();
    let region = MmapRegion::create(1, &Limits::default()).unwrap();
    let mut inst = region
        .new_instance_builder(module)
        .build()
        .unwrap();
    inst.run(b"_start", &[]).unwrap();
}
```

However, I'm getting an error:
```
$ ./target/debug/lucet-example
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DlError(Custom { kind: Other, error: StringError("/stuff/lucet-example/hello.so: undefined symbol: lucet_vmctx_grow_memory") })', src/libcore/result.rs:997:5
```
I can run the module with `lucet-wasi`
```
$ ../lucet/target/release/lucet-wasi hello.so
Hello world!
```
After some poking around I managed to get this to work by adding `lucet-example` crate to `lucet` workspace.

Could you clarify why is this happening and what is a proper way to depend on `lucet-runtime`?

**Comment by pchickey** [comment]
Hi! Thanks for the report.

I believe the problem is that the lucet runtime functions are not in the symbol table used by the runtime linker. This requires certain rustflags be set. We use a `.cargo/config` file at the top level of our project: https://github.com/fastly/lucet/blob/master/.cargo/config

I don't believe we have documentation of this, so we will have to add some. Sorry that you had to find this the hard way!

@acfoltzer-fastly made a report of this issue to the Rust compiler team and hopefully we will get it fixed upstream eventaully.

**Comment by lostman** [comment]
@pchickey Ah that's it, it works now! Thank you for pointing it out. I scoured the project for some sort of linking flags or pragmas but `.cargo/config` is the one place I forgot to look.

👍

**Comment by lostman** [comment]
For the record, the flags are:
```
[build]
rustflags = ["-C", "link-args=-Wl,--export-dynamic"]
```
Adding these to `.cargo/config` in my crate fixed the issue.
